name: Build pyodide wheel

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  PYODIDE_VERSION: 0.26.3
  EMSCRIPTEN_VERSION: 3.1.58

jobs:
  build-pyodide:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: |
          # Match pyodide version
          # https://github.com/posit-dev/shinylive/blob/main/Makefile#L20C19-L20C25
          pip install pyodide-build==0.26.3
          if [ -z "${{ env.EMSCRIPTEN_VERSION }}"]; then
            echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
          fi

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - run: pyodide build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
